--?? 1. SCRIPT ORACLE 19c
--? Tabla de logs
CREATE TABLE TAREA_LOG (
    ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    MENSAJE VARCHAR2(200),
    FECHA_EJECUCION TIMESTAMP DEFAULT SYSTIMESTAMP
);

COMMIT;

--?? Procedimiento que crea y ejecuta el JOB
CREATE OR REPLACE PROCEDURE EJECUTAR_TAREA_AUTOMATICA IS
BEGIN
    INSERT INTO TAREA_LOG (MENSAJE)
    VALUES ('Ejecución directa sin scheduler');
    COMMIT;
END;
/

COMMIT;

SELECT * FROM TAREA_LOG ORDER BY FECHA_EJECUCION DESC;